#include <iostream>
#include <vector>
#include <queue>
#include <set>
#include <stack>
#include <cstring>
#include <string>
#include <algorithm>
using namespace std;

/**
 * Title: 389. Find the Difference
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
 */

/** solution
    XOR
    重复的数字异或为0，a^a=0
 */


/*************************** Submit Part *****************************/
class Solution {
public:
    char findTheDifference(string s, string t) {
        int slen = s.length();
        int tlen = t.length();
        char c = 0;
        for(int i=0; i<slen; ++i)
            c ^= s[i];
        for(int i=0; i<tlen; ++i)
            c ^= t[i];
        return c;
    }
};
/*************************** Submit Part *****************************/

int main()
{
    string s, t;
    cin >> s >> t;

    Solution solution;
    cout << solution.findTheDifference(s, t) << endl;
    return 0;
}
